###

GET http://localhost:3000/student/12345


###

POST http://localhost:3000/student
Content-Type: application/json

{
    "name": "John 444",
    "age": 20,
    "_id": "02221233022"
}

###

PUT http://localhost:3000/student


###

DELETE http://localhost:3000/student

###

GET http://localhost:3000/post